# Generated by Django 6.0.1 on 2026-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Internship')], max_length=20),
        ),
    ]
