# Generated by Django 6.0.1 on 2026-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('COMMUNITY', 'Community Program'), ('VOCATIONAL', 'Vocational training'), ('EDUCATION', 'Eduactional and Skills')], max_length=20)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', help_text="FontAwesome icon class (e.g., 'fas fa-users')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the program without deleting it')),
            ],
        ),
    ]
