# Generated by Django 6.0.1 on 2026-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='https://www.facebook.com/people/Aagaaz-Trust/100094013675364/', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='https://www.instagram.com/aagaaz_charitable_9528/', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/@aagaazcharitabletrust9528', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community Program'), ('VOCATIONAL', 'Vocational training'), ('EDUCATION', 'Educational and Skills')], max_length=20),
        ),
    ]
