# Generated by Django 6.0.1 on 2026-04-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactinfo_facebook_url_contactinfo_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('story_text', models.TextField(help_text='The emotional narrative of how it began')),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('FOUNDER', 'Founding Member'), ('TEACHER', 'Teacher/Staff')], default='TEACHER', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Ashort intro about them')),
                ('order', models.IntegerField(default=0, help_text='Order to display (lower numbers first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
