# Generated by Django 6.0.1 on 2026-05-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aboutus_image_program_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.aboutus')),
            ],
        ),
    ]
