# Generated by Django 6.0.1 on 2026-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aboutgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_slider/')),
            ],
            options={
                'verbose_name_plural': 'Homepage Slider Images',
            },
        ),
    ]
