# Generated by Django 6.0.1 on 2026-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_testimonial_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Former Student, Community Volunteer', max_length=100, null=True),
        ),
    ]
